// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acofmfrbbaotkoubuzns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjb2ZtZnJiYmFvdGtvdWJ1em5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNDM3MzQsImV4cCI6MjA4NTgxOTczNH0.Hz2Swns9pNsNlFPaloo99JhxWPFs7RrDqZbSHQRETmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});